POST http://localhost:8003/api/stream/live
Content-Type: application/json
Accept: text/event-stream

{
  "input":{
    "messages": [
      {
        "content": [
          {
            "type": "text",
            "text": "Apakah BNI dapat melakukan peminjaman seperti untuk cicilan mobil ?"
          }
        ],
        "additional_kwargs": {},
        "response_metadata": {},
        "type": "human",
        "name": null,
        "id": null,
        "example": false
      }
    ],
    "user_id": "USERCISO",
    "session_id": "",
    "divisi_type": "divisi"
  }
}