POST http://localhost:8003/api/stream/live
Content-Type: application/json
Accept: text/event-stream

{
  "input":{
    "messages": [
      {
        "content": [
          {
            "type": "text",
            "text": "Apakah BNI ada cabang di malaysia ?"
          }
        ],
        "additional_kwargs": {},
        "response_metadata": {},
        "type": "human",
        "name": null,
        "id": null,
        "example": false
      }
    ],
    "user_id": "3f0b2d1e-8a9c-4f34-9a7a-2e7b7d0e1234",
    "session_id": "c090366e-9c04-41c4-ace6-f4xa56264190",
    "divisi_type": "divisi"
  }
}