POST https://34.120.254.139/stream_events
Content-Type: application/json
Accept: application/json
X-API-Key: iM8Mgjnm34jxSo9lAsGZr6u7UJ6TnxPtImwnonGg9vAg2Shrnu7zQCM057uQcl1x

{
  "input":{
    "messages": [
      {
        "content": [
          {
            "type": "text",
            "text": "Bagaimana saya mendownload BNI Diva?"
          }
        ],
        "additional_kwargs": {},
        "response_metadata": {},
        "type": "human",
        "name": null,
        "id": null,
        "example": false
      }
    ],
    "user_id": "USERCISO",
    "session_id": "c090366e-9c04-41c4-ace6-f4xa56264097",
    "divisi_type": "divisi"
  }
}